insert into public.projects (
  id,
  title,
  subtitle,
  icon_tone,
  thumbnail,
  type,
  model,
  sort_order,
  dock_order,
  story,
  screenshots,
  demo_url,
  source_url,
  post_id
) values (
  'pricewatch',
  'Pricewatch',
  'A local product watchlist for tracking GBP prices and price history.',
  'graphite',
  '/project-media/pricewatch/pricewatch-logo.png',
  'web app',
  'GPT-6 Astra',
  70,
  null,
  'Pricewatch brings product links into a local watchlist with saved images, GBP price history and the lowest observed price. Browser-assisted checks capture prices from retailer pages and report failures while preserving the last verified observation. Built with React, TypeScript, a Node.js API and SQLite, it keeps the watchlist on your computer.',
  array['/project-media/pricewatch/01-watchlist.png', '/project-media/pricewatch/02-price-history.png', '/project-media/pricewatch/03-add-item.png']::text[],
  null,
  null,
  null
)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  icon_tone = excluded.icon_tone,
  thumbnail = excluded.thumbnail,
  type = excluded.type,
  model = excluded.model,
  sort_order = excluded.sort_order,
  dock_order = excluded.dock_order,
  story = excluded.story,
  screenshots = excluded.screenshots,
  demo_url = excluded.demo_url,
  source_url = excluded.source_url,
  post_id = excluded.post_id;
