insert into public.projects (
  id,
  title,
  subtitle,
  icon_tone,
  thumbnail,
  type,
  model,
  sort_order,
  dock_order,
  story,
  screenshots,
  demo_url,
  source_url,
  post_id
) values (
  'run-visualiser',
  'Run Visualiser',
  'A local Mac app for exploring running trends and reviewing individual runs.',
  'mint',
  'https://twrilkmctqxdizoojgzd.supabase.co/storage/v1/object/public/project-screenshots/run-visualiser/running-journal-logo.png',
  'Mac app',
  'GPT-6 Astra Light',
  60,
  null,
  'Run Visualiser is a local Mac app for reviewing running data imported from Apple Health. Weekly and annual views show distance, time and run counts, while individual run details reveal pace and heart-rate patterns. Built with Swift and a bundled web interface, it reads a local SQLite database without an account or network connection.',
  array['https://twrilkmctqxdizoojgzd.supabase.co/storage/v1/object/public/project-screenshots/run-visualiser/weekly-review.png', 'https://twrilkmctqxdizoojgzd.supabase.co/storage/v1/object/public/project-screenshots/run-visualiser/annual-review.png', 'https://twrilkmctqxdizoojgzd.supabase.co/storage/v1/object/public/project-screenshots/run-visualiser/pace-detail.png']::text[],
  null,
  null,
  null
)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  icon_tone = excluded.icon_tone,
  thumbnail = excluded.thumbnail,
  type = excluded.type,
  model = excluded.model,
  sort_order = excluded.sort_order,
  dock_order = excluded.dock_order,
  story = excluded.story,
  screenshots = excluded.screenshots,
  demo_url = excluded.demo_url,
  source_url = excluded.source_url,
  post_id = excluded.post_id;
